version: 35
jobs:
- name: 更新到其他仓库
  steps:
  - !PushRepository
    name: github
    remoteUrl: https://github.com/zrainpro/shell-ui.git
    passwordSecret: access-token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PushRepository
    name: gitee
    remoteUrl: https://gitee.com/yufo/shell-ui.git
    userName: 雨鱼
    passwordSecret: access-token-gitee
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
